version: '3.1'

services:

  db:
    image: postgres:13.2-alpine
    restart: always
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
    ports:
      - 2100:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 2150:8080
